# This is a basic workflow to help you get started with Actions

name: Sql Script
run-name: Sql Script paractice by ${{github.actor}}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Current 
        run: |
          pwd
      - name: Check directory
        run: |
          ls -a
      - name: Change directory
        run: |
          cd ..
          cd ..
          pwd
          cd ..
          ls -a
          pwd
      - name: Change directory
        run: |
          pwd

      - name: "Script run"
        run: |
          cd ..
          cd ..
          pwd
          cd ..
          cd ..
          cd ..
          cd .local
          ls -a
          pwd
          sqlcmd -S database-1.cqsvhj4w2dhq.us-west-2.rds.amazonaws.com,1433 -U admin -P developer7864 -d Mydb -b -i /home/runner/work/sql_text_script_pipline/src/script/mysql.sql